### ISSUE TITLE
How could I use the stream sending By UnityCam?

### ISSUE THREAD

**Issue by duanyunlun** [mrayy/UnityCam#3]
I'm a new user of this plugins and I dont know how to get the URL of the the WebCam. Should I open the cpp Project to get the source stream?

**Comment by mrayy** [comment]
Sorry for the late reply, but the camera stream will be as a virtual camera you can use in browser or any 3rd party application that supports webcameras

**Comment by PerOveLo** [comment]
Im having trouble using OpenCV and UnityCam. What architecture is used -  MSMF, DSHOW? 
I cant find the UnityCam under Device Manager in windows.  Also the UnityCam path is foo:bar.

I can do image processing on the stream in Matlab, so its probably the setup in OpenCV.
