### ISSUE TITLE
Issues with install

### ISSUE THREAD

**Issue by wtd88** [mrayy/UnityCam#6]
I am having an issue with installing this, I ran the batch script and I am unsure as to where I would find the component. It didn't show up within Unity. I am having a hard time understanding what needs to be done.  Do I need to copy and paste anything into any of the folders, or am I missing something else?Could someone walk me through it one step at a time? 

Thank you in advance!

**Comment by Straafe** [comment]
Open his sample cube scene and just hit run. Then open a browser and go to a site that requires a webcam, then you will see "UnityCam" in the dropdown when the browser asks you if you want to grant the site permissions. Allow it and you will see his test scene in the web page's webcam feed.

**Comment by mrayy** [comment]
When you run the "Register.bat" under the corresponding folder to your OS (x64 for Win10), make sure to right click and choose "Run as administrator". A pop up should show the following message:
"DllRegisterServer in UnityCamService.dll succeeded".

Then as @Straafe mentioned, use a website with camera support such as "https://appr.tc/" and select UnityCam from the camera list.
